name: CI Emscripten

on:
  push:
    paths:
      - 'VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: sudo apt install -y p7zip-full binutils-mips-linux-gnu build-essential pkgconf python3 git zip

      - name: Setup Emscripten
        run: "git clone https://github.com/emscripten-core/emsdk.git .emsdk && cd .emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../"
        
      - name: Build Cores
        run: "source ./.emsdk/emsdk_env.sh && bash build.sh"

      - name: Zip files
        run: "zip -r 'EmulatorJS Cores.zip' EmulatorJS/data/cores/*.data"

      - name: Generate checksums
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            EmulatorJS/data/cores/*.data

      - name: Get Version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> "$GITHUB_OUTPUT"

      - name: Create Release & Make Notes & Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          gh release create "v$VERSION" --title "Latest Version v$VERSION" --generate-notes
          gh release upload "v$VERSION" EmulatorJS/data/cores/*.data
          gh release upload "v$VERSION" "EmulatorJS Cores.zip"
          gh release upload "v$VERSION" "checksum.txt#checksum-256.txt"
