name: CI Emscripten

on:
  push:
    paths:
      - 'VERSION'
      - '.github/workflows/compile.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: sudo apt install -y binutils-mips-linux-gnu build-essential pkgconf python3 git zip

      - name: Setup Emscripten
        run: "git clone https://github.com/emscripten-core/emsdk.git .emsdk && cd .emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../"
        
      - name: Build Cores
        run: "source ./.emsdk/emsdk_env.sh && bash mini_build.sh"

      - name: Zip files
        run: "zip -r EmulatorJS\ Cores.zip EmulatorJS/data/cores/*.data"

      - name: Generate checksums
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            EmulatorJS/data/cores/*.data

      - name: Create Release & Make Notes & Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v1.0" --title "Latest Version" --generate-notes
          gh release upload "v1.0" EmulatorJS/data/cores/*.data
          gh release upload "v1.0" EmulatorJS\ Cores.zip
          gh release upload "v1.0" "checksum.txt#checksum-256.txt"
